---
name: guacho
description: Guacho

base-image: quay.io/fedora-ostree-desktops/base-atomic
image-version: 41

modules:
  - from-file: common/common-modules.yml
  - from-file: common/networking-modules.yml
  - from-file: common/virt-modules.yml
  - from-file: common/greetd-modules.yml
